### ISSUE TITLE
Please provide tags for released versions

### ISSUE THREAD

**Issue by jerboaa** [jfree/jcommon#1]
Hi!

I'm packaging jcommon/jfreechart for Fedora and it would be helpful if released versions (as available on maven central) would get tagged. This simplifies generating a source tarball. In fact, I think github can be used to get a source tarball from a tag via: https://github.com/jfree/jcommon/archive/{tag}.zip

Thanks,
Severin

**Comment by jfree** [comment]
Thanks for the feedback.  Added  a tag for the 1.0.23 release.  I will tag future releases also.

Best regards
David
