### ISSUE TITLE
TextUtilities#drawRotatedString(...) is not using argument textX

### ISSUE THREAD

**Issue by barney2k7** [jfree/jcommon#3]
from https://sourceforge.net/p/jfreechart/bugs/1142/

"In org.jfree.text.TextUtilites I found in the method "public static void drawRotatedString(String text, Graphics2d g2, float textX, float textY, double angle, float rotateX, float rotateY)" a bug:

in the code fragment

```
if (angle == 0.0) {
    drawAlignedString(text, g2, textY, textY, TextAnchor.BASELINE_LEFT);
    return;
}
```

Should the method not called like this (textX was not used):
drawAlignedString(text, g2, textX, textY, TextAnchor.BASELINE_LEFT);"

**Comment by barney2k7** [comment]
Created Pull Request #4

**Comment by jfree** [comment]
Thanks, I merged your pull request.
